/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';

declare let self: ServiceWorkerGlobalScope;

// Precache all assets generated by Vite PWA
precacheAndRoute(self.__WB_MANIFEST || []);

// Handle push event (when receiving notifications in the background or closed app)
self.addEventListener('push', (event) => {
  let data = { title: 'Hay Equipo', body: 'Nueva notificación recibida.', url: '/' };
  try {
    if (event.data) {
      data = event.data.json();
    }
  } catch (e) {
    if (event.data) {
      data = {
        title: 'Hay Equipo',
        body: event.data.text(),
        url: '/'
      };
    }
  }

  const options: NotificationOptions = {
    body: data.body,
    icon: '/logopwa.png',
    badge: '/logopwa.png',
    vibrate: [200, 100, 200],
    data: {
      url: data.url || '/'
    }
  };

  event.waitUntil(
    self.registration.showNotification(data.title, options)
  );
});

// Handle notification click event (re-opening or focusing PWA)
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const urlToOpen = new URL(event.notification.data?.url || '/', self.location.origin).href;

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // Focus if window already exists
      for (const client of windowClients) {
        if (client.url === urlToOpen && 'focus' in client) {
          return client.focus();
        }
      }
      // If no window, open a new one
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});
